// frontend-vue/src/components/Users.vue
<template>
    <div class="users">
        <AvatarIcon icon="✚" icon-type="half" hover="Create account" @click="openUseCreateMenu"/>
        <div class='separate'></div>
        <AvatarUser 
            v-for="user in users"
            :active="user.id === selectedUser?.id"
            :user="user"
            @click="selectUser(user)"
        />
    </div>
</template>

<script lang="ts">
import { Data, User } from '@/utils/Data';
import { defineComponent } from 'vue';
import AvatarIcon from '@/components/AvatarIcon.vue';
import AvatarUser from '@/components/AvatarUser.vue';

interface UserData {
    users: Array<User>,
}

export default defineComponent({
    name: "Users",
    components: {AvatarIcon, AvatarUser},
    data(): UserData {
        return {
            users: []
        }
    },
    props: {
        selectedUser: Object,
    },
    methods: {
        selectUser(user: User) {
            this.$emit("selectUser", user);
        },
        openUseCreateMenu(){
            alert("SUS");
        }
    },
    async mounted() {
        this.users = await Data.getUsers();
    },
})
</script>

<style scoped lang="scss">
.users {
    width: 70px;
    background-color: rgb(72, 56, 143);
    display: flex;
    flex-direction: column;
    .separate {
        height: 2px;
        width: 50%;
        background-color: #666;
        margin: 2px;
        margin-left: auto;
        margin-right: auto;
    }
}
</style>

// frontend-react/src/components/Users.tsx
import './Users.scss';
import axios from "axios";
import { useEffect, useState } from "react";
import { User } from '../Data';

function Avatar(props: {user: User, active: boolean | "half", onClick: () => void}) {
    const active = props.active === true ? "active" : (props.active || "");
    return (
        <Icon className={`avatar ${active}`} 
            hover={props.user.name}
            icon={props.user.name.substring(0, 1)}
            onClick={props.onClick}
        />
    )
}
function Icon(props: {icon?: any, hover: string, className: string, onClick?: () => void}) {
    return (
        <div className={`icon ${props.className}`} onClick={props.onClick}>
            {typeof props.icon === "string" && <p className={`img i${props.icon.length}`}>{props.icon}</p>}
            <p className='name'>{props.hover}</p>
        </div>
    )
}

function Users(props: {selectedUser: User|undefined, selectUser: (user: User) => void}) {
    const {selectedUser, selectUser} = props;
    const [users, setUsers] = useState<Array<User>>([]);
    useEffect(() => {
        axios.get("/api/v1/users").then((resp) => {
            setUsers(resp.data);
        })
    }, [setUsers])
    return (
        <div className="users">
            <Icon icon="✚" className="half" hover="Create account"/>
            <div className='separate'></div>
            {users.map((user, i) => (
                <Avatar key={i} user={user}
                    active={user.id===selectedUser?.id}
                    onClick={() => selectUser(user)}
                />
            ))}
        </div>
    );
}
  
export default Users;
