// frontend-react/src/components/Posts.tsx
import './Posts.scss';
import axios from "axios";
import { useEffect, useState } from "react";
import { Data, Post, User } from '../Data';
import Utils from '../utils/Utils';

const cache = new Map<number, Array<Post>>();

function NewPost(props: {user: User, addPost: (post: Post) => void}) {
    const {user, addPost} = props;
    return (
        <form className='what-new' onSubmit={(event) => {
            event.preventDefault();
            const element = document.querySelector("form.what-new input#post") as HTMLInputElement;
            if (!element) return;
            if (!element.value) return;
            user.lastPostId += 1;
            const post: Post = {
                id: user.lastPostId,
                text: element.value
            };
            element.value = "";
            addPost(post);
        }}>
            <input type="text" placeholder="What's new?" id='post'/>
            <input type='submit' value='Post' className='submit' />
        </form>
    );
}

function Posts(props: {user?: User}) {
    const {user} = props;
    const [posts, setPosts] = useState<Array<Post>|undefined>();

    useEffect(() => {
        if (!user) return;
        if (cache.has(user.id)) setPosts(cache.get(user.id));
        else setPosts(undefined);
        Data.getPosts(user).then(p => {
            if (Utils.equals(posts, p)) return;
            cache.set(user.id, p);
            setPosts(p);
        });
    }, [user, setPosts]);

    if (!user) return (<div className="posts"><h3>Choose account</h3></div>);
    if (!posts) return (<div className="posts"><h3>Loading....</h3></div>);
    if (posts.length===0){
        return (
            <div className="posts">
                {user && <NewPost user={user} addPost={addPost}/>}
                <h3 className='nopost'>No posts</h3>
            </div>
        );
    }
    async function addPost(post: Post) {
        if (!user) return;
        const narr: Post[] = !posts ? [post] : [post, ...posts];
        setPosts(narr);
        cache.set(user.id, narr);
        await Data.createPost(user.id, post.text)
    }
    function deletePost(post: Post) {
        if (!user) return;
        if (!posts) return;
        let narr: Post[] = [...posts];
        narr = narr.filter((p, _) => post.id!==p.id);
        setPosts(narr);
        cache.set(user.id, narr);

        axios.delete(`/api/v1/posts/delete?userid=${user.id}&postid=${post.id}`);
    }
    return (
        <div className="posts">
            {user && <NewPost user={user} addPost={addPost}/>}
            {posts.map((post, i) => (
                <div key={i} className="post">
                    <p>{post.text}</p>
                    <div className='delpost' onClick={() => deletePost(post)}>✖</div>
                </div>
            ))}
        </div>
    );
}
  
export default Posts;

// frontend-vue/src/components/Posts.vue
<template>
    <div v-if="!selectedUser" class="posts">
        <h3>Choose account</h3>
    </div>
    <div v-else-if="posts===null||posts===undefined" class="posts">
        <h3 className='nopost'>Loading... {{selectedUser.name}}</h3>
    </div>
    <div v-else class="posts">
        <h3 v-if="posts.length===0" className='nopost'>No posts</h3>
        <div v-else class="posts">
            <NewPost @createPost="createPost"/>
            <div v-for="post in posts" className="post">
                <p>{{post.id}} {{post.text}}</p>
                <div className='delpost' @click="deletePost(post)">✖</div>
            </div>
        </div>
    </div>
</template>

<script lang="ts">
import { Data, Post, User } from '@/utils/Data';
import { defineComponent } from 'vue';
import NewPost from './NewPost.vue';

interface PostData {
    posts: Post[] | null
}

const cache = new Map<number, Array<Post>>();

export default defineComponent({
    name: "Posts",
    components: {NewPost},
    data(): PostData {
        return {
            posts: null
        }
    },
    props: {
        selectedUser: Object,
    },
    methods: {
        async deletePost(post: Post) {
            if (!this.selectedUser) return;
            if (!this.posts) return;
            this.posts = this.posts.filter((p, _) => post.id!==p.id);
            cache.set(this.selectedUser.id, this.posts);
            await Data.removePost(this.selectedUser.id, post.id);
        },
        async createPost(text: string) {
            if (!this.selectedUser) return;
            const user = this.selectedUser;
            user.lastPostId += 1;
            this.$emit("selectUser", user);
            let post: Post = { id: user.lastPostId, text };
            this.posts = !this.posts ? [post] : [post, ...this.posts]; 
            cache.set(this.selectedUser.id, this.posts);
            await Data.createPost(user.id, post.text);
        },
        async updatePosts() {
            console.log("update");
            if (!this.selectedUser) {
                this.posts = null;
                return;
            }
            this.posts = cache.get(this.selectedUser.id) || this.posts;
            this.posts = await Data.getPosts(this.selectedUser as User);
            cache.set(this.selectedUser.id, this.posts)
        }
    },
    async mounted() {
        this.updatePosts();
    },
    watch: {
        'selectedUser': {
            handler() { this.updatePosts() },
            immediate: true
        }
    }
})
</script>

<style scoped lang="scss">
.posts {
    width: 85%;
    margin-left: auto;
    margin-right: auto;
    .post {
        color: black;
        background-color: white;
        margin-bottom: 10px;
        padding: 5px;
        border-radius: 10px;
        display: flex;
        justify-content: space-between;
        .delpost {
            margin-right: 10px;
            margin-left: 5px;
            color: red;
            cursor: pointer;
            height: 20px;
            user-select: none;
        }
    }
    h3 {
        text-align: center;
        color: white;
    }
}
</style>
